# Generated by Django 4.2.8 on 2026-01-15 11:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("transport", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Colis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Date de dernière modification"
                    ),
                ),
                ("nom_expediteur", models.CharField(max_length=100)),
                ("telephone_expediteur", models.CharField(max_length=20)),
                ("nom_destinataire", models.CharField(max_length=100)),
                ("telephone_destinataire", models.CharField(max_length=20)),
                ("adresse_destinataire", models.TextField()),
                ("description", models.TextField()),
                (
                    "poids",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Poids en kg",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                    ),
                ),
                (
                    "type_colis",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("vetement", "Vêtement"),
                            ("nourriture", "Nourriture"),
                            ("electronique", "Électronique"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=20,
                    ),
                ),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("est_paye", models.BooleanField(default=False)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("enregistre", "Enregistré"),
                            ("en_transit", "En transit"),
                            ("arrive", "Arrivé"),
                            ("livre", "Livré"),
                            ("annule", "Annulé"),
                        ],
                        default="enregistre",
                        max_length=20,
                    ),
                ),
                ("code_suivi", models.CharField(max_length=20, unique=True)),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qrcodes/"),
                ),
                (
                    "destinataire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="colis_recus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expediteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colis_expedies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gare_arrivee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colis_arrivee",
                        to="geography.gare",
                    ),
                ),
                (
                    "gare_depart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colis_depart",
                        to="geography.gare",
                    ),
                ),
                (
                    "trajet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colis",
                        to="transport.trajet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Colis",
                "verbose_name_plural": "Colis",
                "db_table": "delivery_colis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Livraison",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Date de dernière modification"
                    ),
                ),
                ("date_recuperation", models.DateTimeField(blank=True, null=True)),
                ("date_livraison", models.DateTimeField(blank=True, null=True)),
                (
                    "signature_destinataire",
                    models.ImageField(blank=True, null=True, upload_to="signatures/"),
                ),
                ("commentaire", models.TextField(blank=True, null=True)),
                (
                    "colis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livraison",
                        to="delivery.colis",
                    ),
                ),
                (
                    "livreur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="livraisons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Livraison",
                "verbose_name_plural": "Livraisons",
                "db_table": "delivery_livraison",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoriqueEtatColis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Date de dernière modification"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("enregistre", "Enregistré"),
                            ("en_transit", "En transit"),
                            ("arrive", "Arrivé"),
                            ("livre", "Livré"),
                            ("annule", "Annulé"),
                        ],
                        max_length=20,
                    ),
                ),
                ("commentaire", models.TextField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "colis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="delivery.colis",
                    ),
                ),
                (
                    "localisation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="geography.gare",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique État",
                "verbose_name_plural": "Historique États",
                "db_table": "delivery_historique_etat",
                "ordering": ["-created_at"],
            },
        ),
    ]
