# Generated by Django 4.2.8 on 2026-01-15 00:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Date de dernière modification"
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        help_text="Immatriculation", max_length=50, unique=True
                    ),
                ),
                ("modele", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "nombre_places",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Bus",
                "verbose_name_plural": "Bus",
                "db_table": "transport_bus",
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="Compagnie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Date de dernière modification"
                    ),
                ),
                ("nom", models.CharField(max_length=200, unique=True)),
                ("telephone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("adresse", models.TextField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="compagnies/"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Compagnie",
                "verbose_name_plural": "Compagnies",
                "db_table": "transport_compagnie",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Date de dernière modification"
                    ),
                ),
                ("numero_place", models.CharField(max_length=10)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("libre", "Libre"),
                            ("reservee", "Réservée"),
                            ("occupee", "Occupée"),
                        ],
                        default="libre",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Place",
                "verbose_name_plural": "Places",
                "db_table": "transport_place",
                "ordering": ["numero_place"],
            },
        ),
        migrations.CreateModel(
            name="Trajet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Date de dernière modification"
                    ),
                ),
                ("heure_depart", models.TimeField()),
                ("heure_arrivee_estimee", models.TimeField()),
                ("date_depart", models.DateField()),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("places_disponibles", models.IntegerField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("prevu", "Prévu"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("annule", "Annulé"),
                        ],
                        default="prevu",
                        max_length=20,
                    ),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trajets",
                        to="transport.bus",
                    ),
                ),
                (
                    "compagnie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trajets",
                        to="transport.compagnie",
                    ),
                ),
                (
                    "gare_arrivee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trajets_arrivee",
                        to="geography.gare",
                    ),
                ),
                (
                    "gare_depart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trajets_depart",
                        to="geography.gare",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trajet",
                "verbose_name_plural": "Trajets",
                "db_table": "transport_trajet",
                "ordering": ["-date_depart", "heure_depart"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Date de dernière modification"
                    ),
                ),
                ("nom_passager", models.CharField(max_length=100)),
                ("prenom_passager", models.CharField(max_length=100)),
                ("telephone_passager", models.CharField(max_length=20)),
                ("prix_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("est_paye", models.BooleanField(default=False)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("confirmee", "Confirmée"),
                            ("annulee", "Annulée"),
                            ("terminee", "Terminée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("code_reservation", models.CharField(max_length=20, unique=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="transport.place",
                    ),
                ),
                (
                    "trajet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="transport.trajet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réservation",
                "verbose_name_plural": "Réservations",
                "db_table": "transport_reservation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="place",
            name="trajet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="places",
                to="transport.trajet",
            ),
        ),
        migrations.AddField(
            model_name="bus",
            name="compagnie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bus",
                to="transport.compagnie",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="place",
            unique_together={("trajet", "numero_place")},
        ),
    ]
